# Generated by Django 5.2.6 on 2026-06-03 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='followers',
            field=models.ManyToManyField(blank=True, default=0, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
