# Generated by Django 5.2.6 on 2026-06-03 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usermodel_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='followers',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='following',
            field=models.ManyToManyField(blank=True, default=0, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
