# Generated by Django 5.2.6 on 2026-05-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='publications', to='content.publicationtagmodel', verbose_name='Теги'),
        ),
    ]
