# Generated by Django 5.2.6 on 2026-06-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_publicationmodel_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationcommentmodel',
            old_name='autor',
            new_name='author',
        ),
    ]
